= quarkus-camel-jms-xa

This project demonstrates a bug when `quarkus-artemis-jms`, `quarkus-pooled-jms`, `camel-quarkus-jms` and `quakrus-camel-jta` are used in conjunction with XA transactions.

The problem has been fixed. See section <<solution, Solution>>. Thanks and credits for this go to link:https://zhfeng.github.io/[Zheng Feng] who investigated the problem and found the solution.

== Bug description

The transaction stops working correctly when the `concurrentConsumer(...)` on a jms consumer are set to a value `> 9`.

In detail, the XA transaction is not rolled back properly. With more than `9` concurrent consumer, when the transaction aborts, the message is consumed from the JMS address. The expected behaviour is that the message is not consumed and stays in the JMS address.

== Project setup

The application provides two routes:

- route link:src/main/java/de/turing85/quarkus/artemis/xa/FirstJmsRoute.java[] defines a route with `9` concurrent consumers. The consumers are defined in link:src/main/resources/application.properties[] under config-key `application.first-queue.concurrentConsumers`.
- link:src/main/java/de/turing85/quarkus/artemis/xa/SecondJmsRoute.java[] defines a route with `10` concurrent consumers. The consumers are defined in link:src/main/resources/application.properties[] under config-key `application.second-queue.concurrentConsumers`.

Both routes are configured in such a way that they stop if an exception occurs.

== Reproducer

The reproducer is provided in form of tests. The nested tests link:src/test/java/de/turing85/quarkus/artemis/xa/JmsRouteTest.java[].FirstJmsRouteTest and link:src/test/java/de/turing85/quarkus/artemis/xa/JmsRouteTest.java[].SecondJmsRouteTest are carbon-copies of each other. Both classes provide two tests: one happy path test and one rollback test. For SecondJmsRouteTest, the rollback test fails. After the route has been stopped, the message is no longer in the address.

We can run the tests by executing

.Run test
[source, bash]
----
./mvnw clean test
----

Test `SecondRouteTest::rollbackTest` will fail with the following exception:

.Test exception
[source]
----
...
value of: testMessageOnTopic(...)
expected to be true

	at de.turing85.quarkus.artemis.xa.JmsRouteTest$SecondJmsRouteTest.rollbackTest(JmsRouteTest.java:169)
	at [[Reflective call: 2 frames collapsed (https://goo.gl/aH3UyP)]].(:0)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1013)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:827)
	at [[Testing framework: 27 frames collapsed (https://goo.gl/aH3UyP)]].(:0)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at [[Testing framework: 9 frames collapsed (https://goo.gl/aH3UyP)]].(:0)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at [[Testing framework: 9 frames collapsed (https://goo.gl/aH3UyP)]].(:0)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at [[Testing framework: 22 frames collapsed (https://goo.gl/aH3UyP)]].(:0)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
...
----

The other three tests succeed.

== Remarks:
- The project is written for quarkus `3.2.10.Final` (the current LTS), but the same problem is present on the most recent release (quarkus version `3.6.8`, `quarkus-artemis version `3.1.3` and `quarkus-pooled-jms` version `2.3.0`)
- The issue is still present if we use queues instead of topics, see branch `feature/use-queues`

== Solution [[solution]]
To solve the issue, we need the default task executor type to `DefaultTaskExecutorType.ThreadPool` in link:src/main/java/de/turing85/quarkus/artemis/xa/config/EndpointConfig.java[]:

.`EndpointConfig.java`
[code,java]
----
package de.turing85.quarkus.artemis.xa.config;

...
public class EndpointConfig {
  ...

  public void onComponentAdd(@Observes ComponentAddEvent event) {
    if (event.getComponent() instanceof JmsComponent jmsComponent) {
      ...
      jmsComponent.setDefaultTaskExecutorType(DefaultTaskExecutorType.ThreadPool);
      ...
    }
  }
}

----